"""Inicialización de la base de datos

Revision ID: c21751c3eff6
Revises: 
Create Date: 2025-01-13 23:39:08.099158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21751c3eff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametros_agua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('salinidad', sa.Float(), nullable=False),
    sa.Column('cloruro', sa.Float(), nullable=False),
    sa.Column('boro', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametros_climaticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('humedad', sa.Float(), nullable=False),
    sa.Column('precipitaciones', sa.Float(), nullable=False),
    sa.Column('radiacion_global', sa.Float(), nullable=False),
    sa.Column('radiacion_uv', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametros_suelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('humedad', sa.Float(), nullable=False),
    sa.Column('potencial_matrico', sa.Float(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('salinidad', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('especie', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('clima_id', sa.Integer(), nullable=True),
    sa.Column('agua_id', sa.Integer(), nullable=True),
    sa.Column('suelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agua_id'], ['parametros_agua.id'], ),
    sa.ForeignKeyConstraint(['clima_id'], ['parametros_climaticos.id'], ),
    sa.ForeignKeyConstraint(['suelo_id'], ['parametros_suelo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('especie_rangos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('temperatura_min', sa.Float(), nullable=False),
    sa.Column('temperatura_max', sa.Float(), nullable=False),
    sa.Column('ph_min', sa.Float(), nullable=False),
    sa.Column('ph_max', sa.Float(), nullable=False),
    sa.Column('humedad_min', sa.Float(), nullable=False),
    sa.Column('humedad_max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('especie_rangos')
    op.drop_table('modulos')
    op.drop_table('parametros_suelo')
    op.drop_table('parametros_climaticos')
    op.drop_table('parametros_agua')
    # ### end Alembic commands ###
